# Generated by Django 4.0.1 on 2022-01-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=32)),
                ('fromDate', models.DateField()),
                ('fromTime', models.TimeField()),
                ('toDate', models.DateField()),
                ('toTime', models.TimeField()),
                ('deadlineDate', models.DateField()),
                ('deadlineTime', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('event', models.CharField(max_length=32)),
                ('regType', models.CharField(max_length=32)),
                ('groupSize', models.IntegerField()),
            ],
        ),
    ]
