# Generated by Django 4.0.1 on 2022-01-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EM_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=32)),
                ('fromDate', models.DateField()),
                ('fromTime', models.TimeField()),
                ('toDate', models.DateField()),
                ('toTime', models.TimeField()),
                ('deadlineDate', models.DateField()),
                ('deadlineTime', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('eventId', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
