# Generated by Django 4.0.1 on 2022-01-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EM_App', '0002_event_rename_participants_participant_delete_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventId',
            new_name='eventID',
        ),
    ]
